In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17 -0.345430 -0.149870 -0.305086 -0.341923
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-19 -0.639881  0.599171 -0.346439  0.157895
2026-05-20  0.265948 -0.214616 -0.429847  0.273171
2026-05-21 -2.026986  0.683773  0.370402  0.607153
2026-05-22 -1.422112 -1.626872  0.922928  0.863374

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17 -0.345430 -0.149870 -0.305086 -0.341923
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-19 -0.639881  0.599171 -0.346439  0.157895
2026-05-20  0.265948 -0.214616 -0.429847  0.273171
2026-05-21 -2.026986  0.683773  0.370402  0.607153

In [6]:
df.tail()

                   A         B         C         D
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-19 -0.639881  0.599171 -0.346439  0.157895
2026-05-20  0.265948 -0.214616 -0.429847  0.273171
2026-05-21 -2.026986  0.683773  0.370402  0.607153
2026-05-22 -1.422112 -1.626872  0.922928  0.863374

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[-0.34543034, -0.14986971, -0.3050864 , -0.34192275],
       [ 0.46077834, -1.56452417,  0.14079846, -0.1246081 ],
       [-0.63988127,  0.59917061, -0.3464393 ,  0.15789495],
       [ 0.26594796, -0.21461585, -0.42984745,  0.2731713 ],
       [-2.02698616,  0.68377342,  0.37040226,  0.60715255],
       [-1.42211236, -1.62687161,  0.92292804,  0.86337382]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.617947 -0.378823  0.058793  0.239177
std    0.964545  1.012766  0.526488  0.447841
min   -2.026986 -1.626872 -0.429847 -0.341923
25%   -1.226555 -1.227047 -0.336101 -0.053982
50%   -0.492656 -0.182243 -0.082144  0.215533
75%    0.113103  0.411911  0.313001  0.523657
max    0.460778  0.683773  0.922928  0.863374

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A   -0.345430    0.460778   -0.639881    0.265948   -2.026986   -1.422112
B   -0.149870   -1.564524    0.599171   -0.214616    0.683773   -1.626872
C   -0.305086    0.140798   -0.346439   -0.429847    0.370402    0.922928
D   -0.341923   -0.124608    0.157895    0.273171    0.607153    0.863374

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -0.341923 -0.305086 -0.149870 -0.345430
2026-05-18 -0.124608  0.140798 -1.564524  0.460778
2026-05-19  0.157895 -0.346439  0.599171 -0.639881
2026-05-20  0.273171 -0.429847 -0.214616  0.265948
2026-05-21  0.607153  0.370402  0.683773 -2.026986
2026-05-22  0.863374  0.922928 -1.626872 -1.422112

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-22 -1.422112 -1.626872  0.922928  0.863374
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-20  0.265948 -0.214616 -0.429847  0.273171
2026-05-17 -0.345430 -0.149870 -0.305086 -0.341923
2026-05-19 -0.639881  0.599171 -0.346439  0.157895
2026-05-21 -2.026986  0.683773  0.370402  0.607153

In [15]:
df["A"]

2026-05-17   -0.345430
2026-05-18    0.460778
2026-05-19   -0.639881
2026-05-20    0.265948
2026-05-21   -2.026986
2026-05-22   -1.422112
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17   -0.345430
2026-05-18    0.460778
2026-05-19   -0.639881
2026-05-20    0.265948
2026-05-21   -2.026986
2026-05-22   -1.422112
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -0.149870 -0.345430
2026-05-18 -1.564524  0.460778
2026-05-19  0.599171 -0.639881
2026-05-20 -0.214616  0.265948
2026-05-21  0.683773 -2.026986
2026-05-22 -1.626872 -1.422112

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17 -0.345430 -0.149870 -0.305086 -0.341923
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-19 -0.639881  0.599171 -0.346439  0.157895

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17 -0.345430 -0.149870 -0.305086 -0.341923
2026-05-18  0.460778 -1.564524  0.140798 -0.124608
2026-05-19 -0.639881  0.599171 -0.346439  0.157895

In [20]:
df.loc[dates[0]]

A   -0.345430
B   -0.149870
C   -0.305086
D   -0.341923
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17 -0.345430 -0.149870
2026-05-18  0.460778 -1.564524
2026-05-19 -0.639881  0.599171
2026-05-20  0.265948 -0.214616
2026-05-21 -2.026986  0.683773
2026-05-22 -1.422112 -1.626872

In [22]:
df.loc["20260517":"20260519", ["A", "B"]]

                   A         B
2026-05-17 -0.345430 -0.149870
2026-05-18  0.460778 -1.564524
2026-05-19 -0.639881  0.599171