In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  1.092851  1.090218  0.018228 -0.254074
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811
2026-05-20 -1.345082 -0.090605 -0.039175  0.830132
2026-05-21  0.206724  0.878375 -1.934831  1.229112
2026-05-22 -0.778025 -0.504705 -0.758565 -0.800847

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  1.092851  1.090218  0.018228 -0.254074
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811
2026-05-20 -1.345082 -0.090605 -0.039175  0.830132
2026-05-21  0.206724  0.878375 -1.934831  1.229112

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811
2026-05-20 -1.345082 -0.090605 -0.039175  0.830132
2026-05-21  0.206724  0.878375 -1.934831  1.229112
2026-05-22 -0.778025 -0.504705 -0.758565 -0.800847

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[ 1.09285089,  1.09021821,  0.01822818, -0.25407424],
       [-0.68523736,  1.5987576 , -0.06758861,  0.36832431],
       [ 0.12940467,  1.83903575,  1.53658558,  0.51881075],
       [-1.3450821 , -0.0906047 , -0.03917543,  0.83013161],
       [ 0.20672444,  0.87837456, -1.93483122,  1.22911212],
       [-0.77802478, -0.50470459, -0.75856509, -0.80084724]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.229894  0.801846 -0.207558  0.315243
std    0.874164  0.927727  1.133847  0.736791
min   -1.345082 -0.504705 -1.934831 -0.800847
25%   -0.754828  0.151640 -0.585821 -0.098475
50%   -0.277916  0.984296 -0.053382  0.443568
75%    0.187394  1.471623  0.003877  0.752301
max    1.092851  1.839036  1.536586  1.229112

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A    1.092851   -0.685237    0.129405   -1.345082    0.206724   -0.778025
B    1.090218    1.598758    1.839036   -0.090605    0.878375   -0.504705
C    0.018228   -0.067589    1.536586   -0.039175   -1.934831   -0.758565
D   -0.254074    0.368324    0.518811    0.830132    1.229112   -0.800847

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -0.254074  0.018228  1.090218  1.092851
2026-05-18  0.368324 -0.067589  1.598758 -0.685237
2026-05-19  0.518811  1.536586  1.839036  0.129405
2026-05-20  0.830132 -0.039175 -0.090605 -1.345082
2026-05-21  1.229112 -1.934831  0.878375  0.206724
2026-05-22 -0.800847 -0.758565 -0.504705 -0.778025

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-22 -0.778025 -0.504705 -0.758565 -0.800847
2026-05-20 -1.345082 -0.090605 -0.039175  0.830132
2026-05-21  0.206724  0.878375 -1.934831  1.229112
2026-05-17  1.092851  1.090218  0.018228 -0.254074
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811

In [15]:
df["A"]

2026-05-17    1.092851
2026-05-18   -0.685237
2026-05-19    0.129405
2026-05-20   -1.345082
2026-05-21    0.206724
2026-05-22   -0.778025
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17    1.092851
2026-05-18   -0.685237
2026-05-19    0.129405
2026-05-20   -1.345082
2026-05-21    0.206724
2026-05-22   -0.778025
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17  1.090218  1.092851
2026-05-18  1.598758 -0.685237
2026-05-19  1.839036  0.129405
2026-05-20 -0.090605 -1.345082
2026-05-21  0.878375  0.206724
2026-05-22 -0.504705 -0.778025

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17  1.092851  1.090218  0.018228 -0.254074
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17  1.092851  1.090218  0.018228 -0.254074
2026-05-18 -0.685237  1.598758 -0.067589  0.368324
2026-05-19  0.129405  1.839036  1.536586  0.518811

In [20]:
df.loc[dates[0]]

A    1.092851
B    1.090218
C    0.018228
D   -0.254074
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17  1.092851  1.090218
2026-05-18 -0.685237  1.598758
2026-05-19  0.129405  1.839036
2026-05-20 -1.345082 -0.090605
2026-05-21  0.206724  0.878375
2026-05-22 -0.778025 -0.504705