In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17 -0.169712 -0.414671 -1.146815 -0.842660
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
2026-05-20 -1.343448 -0.767639 -1.501292  0.832573
2026-05-21  3.472495  0.354432  0.210545 -0.072325
2026-05-22 -0.476399  1.307388 -1.345943 -0.570784

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17 -0.169712 -0.414671 -1.146815 -0.842660
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
2026-05-20 -1.343448 -0.767639 -1.501292  0.832573
2026-05-21  3.472495  0.354432  0.210545 -0.072325

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
2026-05-20 -1.343448 -0.767639 -1.501292  0.832573
2026-05-21  3.472495  0.354432  0.210545 -0.072325
2026-05-22 -0.476399  1.307388 -1.345943 -0.570784

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[-0.16971223, -0.41467135, -1.14681522, -0.84265974],
       [-1.00601452, -0.01380003, -1.73903378,  0.08195547],
       [ 0.03524502, -0.94352756, -0.43686186, -1.18289885],
       [-1.34344847, -0.76763888, -1.50129168,  0.83257254],
       [ 3.47249474,  0.35443153,  0.21054532, -0.0723245 ],
       [-0.47639939,  1.30738824, -1.34594344, -0.57078433]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.085361 -0.079636 -0.993233 -0.292357
std    1.737148  0.830481  0.737694  0.724901
min   -1.343448 -0.943528 -1.739034 -1.182899
25%   -0.873611 -0.679397 -1.462455 -0.774691
50%   -0.323056 -0.214236 -1.246379 -0.321554
75%   -0.015994  0.262374 -0.614350  0.043385
max    3.472495  1.307388  0.210545  0.832573

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A   -0.169712   -1.006015    0.035245   -1.343448    3.472495   -0.476399
B   -0.414671   -0.013800   -0.943528   -0.767639    0.354432    1.307388
C   -1.146815   -1.739034   -0.436862   -1.501292    0.210545   -1.345943
D   -0.842660    0.081955   -1.182899    0.832573   -0.072325   -0.570784

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -0.842660 -1.146815 -0.414671 -0.169712
2026-05-18  0.081955 -1.739034 -0.013800 -1.006015
2026-05-19 -1.182899 -0.436862 -0.943528  0.035245
2026-05-20  0.832573 -1.501292 -0.767639 -1.343448
2026-05-21 -0.072325  0.210545  0.354432  3.472495
2026-05-22 -0.570784 -1.345943  1.307388 -0.476399

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
2026-05-20 -1.343448 -0.767639 -1.501292  0.832573
2026-05-17 -0.169712 -0.414671 -1.146815 -0.842660
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-21  3.472495  0.354432  0.210545 -0.072325
2026-05-22 -0.476399  1.307388 -1.345943 -0.570784

In [15]:
df["A"]

2026-05-17   -0.169712
2026-05-18   -1.006015
2026-05-19    0.035245
2026-05-20   -1.343448
2026-05-21    3.472495
2026-05-22   -0.476399
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17   -0.169712
2026-05-18   -1.006015
2026-05-19    0.035245
2026-05-20   -1.343448
2026-05-21    3.472495
2026-05-22   -0.476399
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -0.414671 -0.169712
2026-05-18 -0.013800 -1.006015
2026-05-19 -0.943528  0.035245
2026-05-20 -0.767639 -1.343448
2026-05-21  0.354432  3.472495
2026-05-22  1.307388 -0.476399

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17 -0.169712 -0.414671 -1.146815 -0.842660
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17 -0.169712 -0.414671 -1.146815 -0.842660
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899

In [20]:
df.loc[dates[0]]

A   -0.169712
B   -0.414671
C   -1.146815
D   -0.842660
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17 -0.169712 -0.414671
2026-05-18 -1.006015 -0.013800
2026-05-19  0.035245 -0.943528
2026-05-20 -1.343448 -0.767639
2026-05-21  3.472495  0.354432
2026-05-22 -0.476399  1.307388

In [22]:
df.loc["20260517":"20260519", ["A", "B"]]

                   A         B
2026-05-17 -0.169712 -0.414671
2026-05-18 -1.006015 -0.013800
2026-05-19  0.035245 -0.943528

In [23]:
df.loc[dates[0],"A"]

np.float64(-0.16971222593567103)

In [24]:
df.at[dates[0],"A"]

np.float64(-0.16971222593567103)

In [25]:
print(df.iloc[3])
print(df.iloc[3:5,0:2])
print(df.iloc[[1,2,4],[0,2]])
print(df.iloc[1:3,:])
print(df.iloc[:,1:3])
print(df.iloc[1,1])
print(df.iat[1,1])

A   -1.343448
B   -0.767639
C   -1.501292
D    0.832573
Name: 2026-05-20 00:00:00, dtype: float64
                   A         B
2026-05-20 -1.343448 -0.767639
2026-05-21  3.472495  0.354432
                   A         C
2026-05-18 -1.006015 -1.739034
2026-05-19  0.035245 -0.436862
2026-05-21  3.472495  0.210545
                   A         B         C         D
2026-05-18 -1.006015 -0.013800 -1.739034  0.081955
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
                   B         C
2026-05-17 -0.414671 -1.146815
2026-05-18 -0.013800 -1.739034
2026-05-19 -0.943528 -0.436862
2026-05-20 -0.767639 -1.501292
2026-05-21  0.354432  0.210545
2026-05-22  1.307388 -1.345943
-0.013800027781930091
-0.013800027781930091

In [26]:
df[df["A"] > 0]

                   A         B         C         D
2026-05-19  0.035245 -0.943528 -0.436862 -1.182899
2026-05-21  3.472495  0.354432  0.210545 -0.072325

In [27]:
df[df > 0]

                   A         B         C         D
2026-05-17       NaN       NaN       NaN       NaN
2026-05-18       NaN       NaN       NaN  0.081955
2026-05-19  0.035245       NaN       NaN       NaN
2026-05-20       NaN       NaN       NaN  0.832573
2026-05-21  3.472495  0.354432  0.210545       NaN
2026-05-22       NaN  1.307388       NaN       NaN