In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  0.920914 -0.483945  0.352031  0.096245
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-19 -1.632603  0.325694  0.107995 -0.320469
2026-05-20 -0.068566  0.017868  0.005578  0.011933
2026-05-21  0.112892 -1.346991 -0.381946  1.456211
2026-05-22 -0.507624 -0.020832  0.120474 -1.581721

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  0.920914 -0.483945  0.352031  0.096245
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-19 -1.632603  0.325694  0.107995 -0.320469
2026-05-20 -0.068566  0.017868  0.005578  0.011933
2026-05-21  0.112892 -1.346991 -0.381946  1.456211

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-19 -1.632603  0.325694  0.107995 -0.320469
2026-05-20 -0.068566  0.017868  0.005578  0.011933
2026-05-21  0.112892 -1.346991 -0.381946  1.456211
2026-05-22 -0.507624 -0.020832  0.120474 -1.581721

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[ 0.92091416, -0.48394539,  0.35203112,  0.09624542],
       [-0.10464426, -2.21170336, -1.44602352,  0.25341084],
       [-1.6326026 ,  0.3256937 ,  0.10799468, -0.32046949],
       [-0.06856619,  0.01786821,  0.00557837,  0.01193315],
       [ 0.11289217, -1.3469913 , -0.3819459 ,  1.45621136],
       [-0.50762436, -0.02083167,  0.12047388, -1.58172138]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.213272 -0.619985 -0.206982 -0.014065
std    0.839839  0.973731  0.652679  0.979544
min   -1.632603 -2.211703 -1.446024 -1.581721
25%   -0.406879 -1.131230 -0.285065 -0.237369
50%   -0.086605 -0.252389  0.056787  0.054089
75%    0.067528  0.008193  0.117354  0.214119
max    0.920914  0.325694  0.352031  1.456211

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A    0.920914   -0.104644   -1.632603   -0.068566    0.112892   -0.507624
B   -0.483945   -2.211703    0.325694    0.017868   -1.346991   -0.020832
C    0.352031   -1.446024    0.107995    0.005578   -0.381946    0.120474
D    0.096245    0.253411   -0.320469    0.011933    1.456211   -1.581721

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17  0.096245  0.352031 -0.483945  0.920914
2026-05-18  0.253411 -1.446024 -2.211703 -0.104644
2026-05-19 -0.320469  0.107995  0.325694 -1.632603
2026-05-20  0.011933  0.005578  0.017868 -0.068566
2026-05-21  1.456211 -0.381946 -1.346991  0.112892
2026-05-22 -1.581721  0.120474 -0.020832 -0.507624

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-21  0.112892 -1.346991 -0.381946  1.456211
2026-05-17  0.920914 -0.483945  0.352031  0.096245
2026-05-22 -0.507624 -0.020832  0.120474 -1.581721
2026-05-20 -0.068566  0.017868  0.005578  0.011933
2026-05-19 -1.632603  0.325694  0.107995 -0.320469

In [15]:
df["A"]

2026-05-17    0.920914
2026-05-18   -0.104644
2026-05-19   -1.632603
2026-05-20   -0.068566
2026-05-21    0.112892
2026-05-22   -0.507624
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17    0.920914
2026-05-18   -0.104644
2026-05-19   -1.632603
2026-05-20   -0.068566
2026-05-21    0.112892
2026-05-22   -0.507624
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -0.483945  0.920914
2026-05-18 -2.211703 -0.104644
2026-05-19  0.325694 -1.632603
2026-05-20  0.017868 -0.068566
2026-05-21 -1.346991  0.112892
2026-05-22 -0.020832 -0.507624

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17  0.920914 -0.483945  0.352031  0.096245
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-19 -1.632603  0.325694  0.107995 -0.320469

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17  0.920914 -0.483945  0.352031  0.096245
2026-05-18 -0.104644 -2.211703 -1.446024  0.253411
2026-05-19 -1.632603  0.325694  0.107995 -0.320469

In [20]:
df.loc[dates[0]]

A    0.920914
B   -0.483945
C    0.352031
D    0.096245
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17  0.920914 -0.483945
2026-05-18 -0.104644 -2.211703
2026-05-19 -1.632603  0.325694
2026-05-20 -0.068566  0.017868
2026-05-21  0.112892 -1.346991
2026-05-22 -0.507624 -0.020832

In [22]:
df.loc["20260517":"20260519", ["A", "B"]]

                   A         B
2026-05-17  0.920914 -0.483945
2026-05-18 -0.104644 -2.211703
2026-05-19 -1.632603  0.325694

In [23]:
df.loc[dates[0],"A"]

np.float64(0.9209141555065936)

In [24]:
df.at[dates[0],"A"]

np.float64(0.9209141555065936)