In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17 -0.364606 -1.704396  1.887164 -0.696392
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-19 -1.233954  2.851046  0.699531 -1.638927
2026-05-20  0.472564 -0.382065  0.191262 -0.546652
2026-05-21 -0.007256  1.702883 -1.569120 -1.337163
2026-05-22  0.564202 -0.609305  2.694806 -0.187538

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17 -0.364606 -1.704396  1.887164 -0.696392
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-19 -1.233954  2.851046  0.699531 -1.638927
2026-05-20  0.472564 -0.382065  0.191262 -0.546652
2026-05-21 -0.007256  1.702883 -1.569120 -1.337163

In [6]:
df.tail()

                   A         B         C         D
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-19 -1.233954  2.851046  0.699531 -1.638927
2026-05-20  0.472564 -0.382065  0.191262 -0.546652
2026-05-21 -0.007256  1.702883 -1.569120 -1.337163
2026-05-22  0.564202 -0.609305  2.694806 -0.187538

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[-0.3646057 , -1.70439605,  1.88716425, -0.69639205],
       [ 0.42131797, -0.36103673, -0.38494093, -0.66227993],
       [-1.23395412,  2.8510463 ,  0.69953137, -1.63892656],
       [ 0.47256389, -0.38206538,  0.19126214, -0.54665245],
       [-0.0072559 ,  1.70288283, -1.56911984, -1.33716327],
       [ 0.56420166, -0.60930503,  2.69480574, -0.18753777]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.024622  0.249521  0.586450 -0.844825
std    0.688643  1.685660  1.542470  0.538383
min   -1.233954 -1.704396 -1.569120 -1.638927
25%   -0.275268 -0.552495 -0.240890 -1.176970
50%    0.207031 -0.371551  0.445397 -0.679336
75%    0.459752  1.186903  1.590256 -0.575559
max    0.564202  2.851046  2.694806 -0.187538

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A   -0.364606    0.421318   -1.233954    0.472564   -0.007256    0.564202
B   -1.704396   -0.361037    2.851046   -0.382065    1.702883   -0.609305
C    1.887164   -0.384941    0.699531    0.191262   -1.569120    2.694806
D   -0.696392   -0.662280   -1.638927   -0.546652   -1.337163   -0.187538

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -0.696392  1.887164 -1.704396 -0.364606
2026-05-18 -0.662280 -0.384941 -0.361037  0.421318
2026-05-19 -1.638927  0.699531  2.851046 -1.233954
2026-05-20 -0.546652  0.191262 -0.382065  0.472564
2026-05-21 -1.337163 -1.569120  1.702883 -0.007256
2026-05-22 -0.187538  2.694806 -0.609305  0.564202

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-17 -0.364606 -1.704396  1.887164 -0.696392
2026-05-22  0.564202 -0.609305  2.694806 -0.187538
2026-05-20  0.472564 -0.382065  0.191262 -0.546652
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-21 -0.007256  1.702883 -1.569120 -1.337163
2026-05-19 -1.233954  2.851046  0.699531 -1.638927

In [15]:
df["A"]

2026-05-17   -0.364606
2026-05-18    0.421318
2026-05-19   -1.233954
2026-05-20    0.472564
2026-05-21   -0.007256
2026-05-22    0.564202
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17   -0.364606
2026-05-18    0.421318
2026-05-19   -1.233954
2026-05-20    0.472564
2026-05-21   -0.007256
2026-05-22    0.564202
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -1.704396 -0.364606
2026-05-18 -0.361037  0.421318
2026-05-19  2.851046 -1.233954
2026-05-20 -0.382065  0.472564
2026-05-21  1.702883 -0.007256
2026-05-22 -0.609305  0.564202

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17 -0.364606 -1.704396  1.887164 -0.696392
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-19 -1.233954  2.851046  0.699531 -1.638927

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17 -0.364606 -1.704396  1.887164 -0.696392
2026-05-18  0.421318 -0.361037 -0.384941 -0.662280
2026-05-19 -1.233954  2.851046  0.699531 -1.638927