In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17 -0.136721  0.112822 -0.184057 -0.190624
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912
2026-05-20  0.216064 -0.379345 -1.509507  0.912663
2026-05-21 -0.566767  0.078963 -1.174931 -0.747087
2026-05-22  0.119373 -2.062499  0.313064  0.341952

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17 -0.136721  0.112822 -0.184057 -0.190624
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912
2026-05-20  0.216064 -0.379345 -1.509507  0.912663
2026-05-21 -0.566767  0.078963 -1.174931 -0.747087

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912
2026-05-20  0.216064 -0.379345 -1.509507  0.912663
2026-05-21 -0.566767  0.078963 -1.174931 -0.747087
2026-05-22  0.119373 -2.062499  0.313064  0.341952

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[-0.13672052,  0.11282235, -0.1840573 , -0.1906239 ],
       [-0.26371038, -0.07288253,  1.4379387 , -0.67553921],
       [-1.44812001, -1.1931411 , -3.06093877, -0.810912  ],
       [ 0.21606372, -0.37934492, -1.50950687,  0.91266338],
       [-0.56676694,  0.07896314, -1.1749305 , -0.74708656],
       [ 0.11937275, -2.06249862,  0.31306412,  0.341952  ]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.346647 -0.586014 -0.696405 -0.194924
std    0.607694  0.870080  1.569592  0.697183
min   -1.448120 -2.062499 -3.060939 -0.810912
25%   -0.491003 -0.989692 -1.425863 -0.729200
50%   -0.200215 -0.226114 -0.679494 -0.433082
75%    0.055349  0.041002  0.188784  0.208808
max    0.216064  0.112822  1.437939  0.912663

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A   -0.136721   -0.263710   -1.448120    0.216064   -0.566767    0.119373
B    0.112822   -0.072883   -1.193141   -0.379345    0.078963   -2.062499
C   -0.184057    1.437939   -3.060939   -1.509507   -1.174931    0.313064
D   -0.190624   -0.675539   -0.810912    0.912663   -0.747087    0.341952

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -0.190624 -0.184057  0.112822 -0.136721
2026-05-18 -0.675539  1.437939 -0.072883 -0.263710
2026-05-19 -0.810912 -3.060939 -1.193141 -1.448120
2026-05-20  0.912663 -1.509507 -0.379345  0.216064
2026-05-21 -0.747087 -1.174931  0.078963 -0.566767
2026-05-22  0.341952  0.313064 -2.062499  0.119373

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-22  0.119373 -2.062499  0.313064  0.341952
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912
2026-05-20  0.216064 -0.379345 -1.509507  0.912663
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-21 -0.566767  0.078963 -1.174931 -0.747087
2026-05-17 -0.136721  0.112822 -0.184057 -0.190624

In [15]:
df["A"]

2026-05-17   -0.136721
2026-05-18   -0.263710
2026-05-19   -1.448120
2026-05-20    0.216064
2026-05-21   -0.566767
2026-05-22    0.119373
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17   -0.136721
2026-05-18   -0.263710
2026-05-19   -1.448120
2026-05-20    0.216064
2026-05-21   -0.566767
2026-05-22    0.119373
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17  0.112822 -0.136721
2026-05-18 -0.072883 -0.263710
2026-05-19 -1.193141 -1.448120
2026-05-20 -0.379345  0.216064
2026-05-21  0.078963 -0.566767
2026-05-22 -2.062499  0.119373

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17 -0.136721  0.112822 -0.184057 -0.190624
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17 -0.136721  0.112822 -0.184057 -0.190624
2026-05-18 -0.263710 -0.072883  1.437939 -0.675539
2026-05-19 -1.448120 -1.193141 -3.060939 -0.810912

In [20]:
df.loc[dates[0]]

A   -0.136721
B    0.112822
C   -0.184057
D   -0.190624
Name: 2026-05-17 00:00:00, dtype: float64