In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  0.516925 -0.960484  0.251330  0.968866
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874
2026-05-20 -0.103573  0.694118  0.196485  0.675696
2026-05-21  0.989875  0.708417 -0.254411  0.129175
2026-05-22  1.045407 -0.606933  0.334710  1.100178

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  0.516925 -0.960484  0.251330  0.968866
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874
2026-05-20 -0.103573  0.694118  0.196485  0.675696
2026-05-21  0.989875  0.708417 -0.254411  0.129175

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874
2026-05-20 -0.103573  0.694118  0.196485  0.675696
2026-05-21  0.989875  0.708417 -0.254411  0.129175
2026-05-22  1.045407 -0.606933  0.334710  1.100178

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[ 0.516925  , -0.96048434,  0.25133021,  0.9688656 ],
       [-0.71265726, -0.99072674,  0.52979965, -0.35697705],
       [-0.21493536, -1.27483082,  1.39994058, -0.30687362],
       [-0.10357256,  0.6941178 ,  0.196485  ,  0.67569606],
       [ 0.98987516,  0.70841712, -0.25441068,  0.12917472],
       [ 1.04540741, -0.60693273,  0.33470991,  1.10017776]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.253507 -0.405073  0.409642  0.368344
std    0.709810  0.882811  0.549947  0.637163
min   -0.712657 -1.274831 -0.254411 -0.356977
25%   -0.187095 -0.983166  0.210196 -0.197862
50%    0.206676 -0.783709  0.293020  0.402435
75%    0.871638  0.368855  0.481027  0.895573
max    1.045407  0.708417  1.399941  1.100178

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A    0.516925   -0.712657   -0.214935   -0.103573    0.989875    1.045407
B   -0.960484   -0.990727   -1.274831    0.694118    0.708417   -0.606933
C    0.251330    0.529800    1.399941    0.196485   -0.254411    0.334710
D    0.968866   -0.356977   -0.306874    0.675696    0.129175    1.100178

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17  0.968866  0.251330 -0.960484  0.516925
2026-05-18 -0.356977  0.529800 -0.990727 -0.712657
2026-05-19 -0.306874  1.399941 -1.274831 -0.214935
2026-05-20  0.675696  0.196485  0.694118 -0.103573
2026-05-21  0.129175 -0.254411  0.708417  0.989875
2026-05-22  1.100178  0.334710 -0.606933  1.045407

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-17  0.516925 -0.960484  0.251330  0.968866
2026-05-22  1.045407 -0.606933  0.334710  1.100178
2026-05-20 -0.103573  0.694118  0.196485  0.675696
2026-05-21  0.989875  0.708417 -0.254411  0.129175

In [15]:
df["A"]

2026-05-17    0.516925
2026-05-18   -0.712657
2026-05-19   -0.214935
2026-05-20   -0.103573
2026-05-21    0.989875
2026-05-22    1.045407
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17    0.516925
2026-05-18   -0.712657
2026-05-19   -0.214935
2026-05-20   -0.103573
2026-05-21    0.989875
2026-05-22    1.045407
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -0.960484  0.516925
2026-05-18 -0.990727 -0.712657
2026-05-19 -1.274831 -0.214935
2026-05-20  0.694118 -0.103573
2026-05-21  0.708417  0.989875
2026-05-22 -0.606933  1.045407

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17  0.516925 -0.960484  0.251330  0.968866
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17  0.516925 -0.960484  0.251330  0.968866
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874

In [20]:
df.loc[dates[0]]

A    0.516925
B   -0.960484
C    0.251330
D    0.968866
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17  0.516925 -0.960484
2026-05-18 -0.712657 -0.990727
2026-05-19 -0.214935 -1.274831
2026-05-20 -0.103573  0.694118
2026-05-21  0.989875  0.708417
2026-05-22  1.045407 -0.606933

In [22]:
df.loc["20260517":"20260519", ["A", "B"]]

                   A         B
2026-05-17  0.516925 -0.960484
2026-05-18 -0.712657 -0.990727
2026-05-19 -0.214935 -1.274831

In [23]:
df.loc[dates[0],"A"]

np.float64(0.5169250045535145)

In [24]:
df.at[dates[0],"A"]

np.float64(0.5169250045535145)

In [25]:
print(df.iloc[3])
print(df.iloc[3:5,0:2])
print(df.iloc[[1,2,4],[0,2]])
print(df.iloc[1:3,:])
print(df.iloc[:,1:3])
print(df.iloc[1,1])
print(df.iat[1,1])

A   -0.103573
B    0.694118
C    0.196485
D    0.675696
Name: 2026-05-20 00:00:00, dtype: float64
                   A         B
2026-05-20 -0.103573  0.694118
2026-05-21  0.989875  0.708417
                   A         C
2026-05-18 -0.712657  0.529800
2026-05-19 -0.214935  1.399941
2026-05-21  0.989875 -0.254411
                   A         B         C         D
2026-05-18 -0.712657 -0.990727  0.529800 -0.356977
2026-05-19 -0.214935 -1.274831  1.399941 -0.306874
                   B         C
2026-05-17 -0.960484  0.251330
2026-05-18 -0.990727  0.529800
2026-05-19 -1.274831  1.399941
2026-05-20  0.694118  0.196485
2026-05-21  0.708417 -0.254411
2026-05-22 -0.606933  0.334710
-0.9907267439659574
-0.9907267439659574