In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  0.418696  0.665760  0.228820 -1.046594
2026-05-18 -2.237819 -0.416217  0.170965 -0.659384
2026-05-19 -0.557958  2.310794  1.592003 -0.349697
2026-05-20 -0.723182  0.688848  0.599683 -0.217308
2026-05-21 -1.089609 -1.854868 -0.397617 -0.803127
2026-05-22  0.289478 -0.331584 -0.134609 -0.815134

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  0.418696  0.665760  0.228820 -1.046594
2026-05-18 -2.237819 -0.416217  0.170965 -0.659384
2026-05-19 -0.557958  2.310794  1.592003 -0.349697
2026-05-20 -0.723182  0.688848  0.599683 -0.217308
2026-05-21 -1.089609 -1.854868 -0.397617 -0.803127

In [6]:
df.tail()

                   A         B         C         D
2026-05-18 -2.237819 -0.416217  0.170965 -0.659384
2026-05-19 -0.557958  2.310794  1.592003 -0.349697
2026-05-20 -0.723182  0.688848  0.599683 -0.217308
2026-05-21 -1.089609 -1.854868 -0.397617 -0.803127
2026-05-22  0.289478 -0.331584 -0.134609 -0.815134

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[ 0.41869585,  0.66575993,  0.22882045, -1.04659388],
       [-2.2378194 , -0.41621686,  0.17096543, -0.65938352],
       [-0.55795795,  2.31079352,  1.5920029 , -0.34969662],
       [-0.72318225,  0.68884823,  0.59968287, -0.21730829],
       [-1.08960888, -1.85486754, -0.39761698, -0.80312657],
       [ 0.28947778, -0.33158437, -0.13460917, -0.81513425]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.650066  0.177122  0.343208 -0.648541
std    0.974985  1.399500  0.699307  0.311603
min   -2.237819 -1.854868 -0.397617 -1.046594
25%   -0.998002 -0.395059 -0.058216 -0.812132
50%   -0.640570  0.167088  0.199893 -0.731255
75%    0.077619  0.683076  0.506967 -0.427118
max    0.418696  2.310794  1.592003 -0.217308

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A    0.418696   -2.237819   -0.557958   -0.723182   -1.089609    0.289478
B    0.665760   -0.416217    2.310794    0.688848   -1.854868   -0.331584
C    0.228820    0.170965    1.592003    0.599683   -0.397617   -0.134609
D   -1.046594   -0.659384   -0.349697   -0.217308   -0.803127   -0.815134

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17 -1.046594  0.228820  0.665760  0.418696
2026-05-18 -0.659384  0.170965 -0.416217 -2.237819
2026-05-19 -0.349697  1.592003  2.310794 -0.557958
2026-05-20 -0.217308  0.599683  0.688848 -0.723182
2026-05-21 -0.803127 -0.397617 -1.854868 -1.089609
2026-05-22 -0.815134 -0.134609 -0.331584  0.289478

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-21 -1.089609 -1.854868 -0.397617 -0.803127
2026-05-18 -2.237819 -0.416217  0.170965 -0.659384
2026-05-22  0.289478 -0.331584 -0.134609 -0.815134
2026-05-17  0.418696  0.665760  0.228820 -1.046594
2026-05-20 -0.723182  0.688848  0.599683 -0.217308
2026-05-19 -0.557958  2.310794  1.592003 -0.349697

In [15]:
df["A"]

2026-05-17    0.418696
2026-05-18   -2.237819
2026-05-19   -0.557958
2026-05-20   -0.723182
2026-05-21   -1.089609
2026-05-22    0.289478
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17    0.418696
2026-05-18   -2.237819
2026-05-19   -0.557958
2026-05-20   -0.723182
2026-05-21   -1.089609
2026-05-22    0.289478
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17  0.665760  0.418696
2026-05-18 -0.416217 -2.237819
2026-05-19  2.310794 -0.557958
2026-05-20  0.688848 -0.723182
2026-05-21 -1.854868 -1.089609
2026-05-22 -0.331584  0.289478