In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-20 -0.748144 -1.121230  1.400118 -2.110272
2026-05-21  1.620234 -0.594927 -0.818946  2.350591
2026-05-22  0.927158  0.709709 -2.151795  1.164594

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-20 -0.748144 -1.121230  1.400118 -2.110272
2026-05-21  1.620234 -0.594927 -0.818946  2.350591

In [6]:
df.tail()

                   A         B         C         D
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-20 -0.748144 -1.121230  1.400118 -2.110272
2026-05-21  1.620234 -0.594927 -0.818946  2.350591
2026-05-22  0.927158  0.709709 -2.151795  1.164594

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[ 0.35444655, -0.11578292,  0.28076596,  1.25898582],
       [ 0.29220364, -0.49414653,  2.28110379, -1.78747741],
       [ 0.93936312,  0.57986654,  1.36762766,  1.01063848],
       [-0.74814363, -1.12123023,  1.40011801, -2.11027164],
       [ 1.62023431, -0.59492735, -0.81894587,  2.35059112],
       [ 0.92715764,  0.70970895, -2.15179503,  1.16459382]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.564210 -0.172752  0.393146  0.314510
std    0.803482  0.711274  1.642347  1.818946
min   -0.748144 -1.121230 -2.151795 -2.110272
25%    0.307764 -0.569732 -0.544018 -1.087948
50%    0.640802 -0.304965  0.824197  1.087616
75%    0.936312  0.405954  1.391995  1.235388
max    1.620234  0.709709  2.281104  2.350591

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A    0.354447    0.292204    0.939363   -0.748144    1.620234    0.927158
B   -0.115783   -0.494147    0.579867   -1.121230   -0.594927    0.709709
C    0.280766    2.281104    1.367628    1.400118   -0.818946   -2.151795
D    1.258986   -1.787477    1.010638   -2.110272    2.350591    1.164594

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17  1.258986  0.280766 -0.115783  0.354447
2026-05-18 -1.787477  2.281104 -0.494147  0.292204
2026-05-19  1.010638  1.367628  0.579867  0.939363
2026-05-20 -2.110272  1.400118 -1.121230 -0.748144
2026-05-21  2.350591 -0.818946 -0.594927  1.620234
2026-05-22  1.164594 -2.151795  0.709709  0.927158

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-20 -0.748144 -1.121230  1.400118 -2.110272
2026-05-21  1.620234 -0.594927 -0.818946  2.350591
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-22  0.927158  0.709709 -2.151795  1.164594

In [15]:
df["A"]

2026-05-17    0.354447
2026-05-18    0.292204
2026-05-19    0.939363
2026-05-20   -0.748144
2026-05-21    1.620234
2026-05-22    0.927158
Freq: D, Name: A, dtype: float64

In [16]:
df.A

2026-05-17    0.354447
2026-05-18    0.292204
2026-05-19    0.939363
2026-05-20   -0.748144
2026-05-21    1.620234
2026-05-22    0.927158
Freq: D, Name: A, dtype: float64

In [17]:
df[["B","A"]]

                   B         A
2026-05-17 -0.115783  0.354447
2026-05-18 -0.494147  0.292204
2026-05-19  0.579867  0.939363
2026-05-20 -1.121230 -0.748144
2026-05-21 -0.594927  1.620234
2026-05-22  0.709709  0.927158

In [18]:
df[0:3]

                   A         B         C         D
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638

In [19]:
df["20260517":"20260519"]

                   A         B         C         D
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638

In [20]:
df.loc[dates[0]]

A    0.354447
B   -0.115783
C    0.280766
D    1.258986
Name: 2026-05-17 00:00:00, dtype: float64

In [21]:
df.loc[:, ["A", "B"]]

                   A         B
2026-05-17  0.354447 -0.115783
2026-05-18  0.292204 -0.494147
2026-05-19  0.939363  0.579867
2026-05-20 -0.748144 -1.121230
2026-05-21  1.620234 -0.594927
2026-05-22  0.927158  0.709709

In [22]:
df.loc["20260517":"20260519", ["A", "B"]]

                   A         B
2026-05-17  0.354447 -0.115783
2026-05-18  0.292204 -0.494147
2026-05-19  0.939363  0.579867

In [23]:
df.loc[dates[0],"A"]

np.float64(0.354446553640545)

In [24]:
df.at[dates[0],"A"]

np.float64(0.354446553640545)

In [25]:
print(df.iloc[3])
print(df.iloc[3:5,0:2])
print(df.iloc[[1,2,4],[0,2]])
print(df.iloc[1:3,:])
print(df.iloc[:,1:3])
print(df.iloc[1,1])
print(df.iat[1,1])

A   -0.748144
B   -1.121230
C    1.400118
D   -2.110272
Name: 2026-05-20 00:00:00, dtype: float64
                   A         B
2026-05-20 -0.748144 -1.121230
2026-05-21  1.620234 -0.594927
                   A         C
2026-05-18  0.292204  2.281104
2026-05-19  0.939363  1.367628
2026-05-21  1.620234 -0.818946
                   A         B         C         D
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638
                   B         C
2026-05-17 -0.115783  0.280766
2026-05-18 -0.494147  2.281104
2026-05-19  0.579867  1.367628
2026-05-20 -1.121230  1.400118
2026-05-21 -0.594927 -0.818946
2026-05-22  0.709709 -2.151795
-0.49414653446270435
-0.49414653446270435

In [26]:
df[df["A"] > 0]

                   A         B         C         D
2026-05-17  0.354447 -0.115783  0.280766  1.258986
2026-05-18  0.292204 -0.494147  2.281104 -1.787477
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-21  1.620234 -0.594927 -0.818946  2.350591
2026-05-22  0.927158  0.709709 -2.151795  1.164594

In [27]:
df[df > 0]

                   A         B         C         D
2026-05-17  0.354447       NaN  0.280766  1.258986
2026-05-18  0.292204       NaN  2.281104       NaN
2026-05-19  0.939363  0.579867  1.367628  1.010638
2026-05-20       NaN       NaN  1.400118       NaN
2026-05-21  1.620234       NaN       NaN  2.350591
2026-05-22  0.927158  0.709709       NaN  1.164594

In [28]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2[df2["E"].isin(["two", "four"])]

                   A         B         C         D     E
2026-05-19  0.939363  0.579867  1.367628  1.010638   two
2026-05-21  1.620234 -0.594927 -0.818946  2.350591  four