In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17  2.209774  0.413596 -0.858573 -0.228326
2026-05-18  0.605085 -0.839232 -0.581135  0.229926
2026-05-19  0.615083  0.181806  0.480017 -0.055614
2026-05-20 -1.873690 -0.581555 -0.151738 -0.640246
2026-05-21  0.001949 -0.657578 -1.566766  1.551523
2026-05-22  1.045312  0.555394  1.187360 -1.022541

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17  2.209774  0.413596 -0.858573 -0.228326
2026-05-18  0.605085 -0.839232 -0.581135  0.229926
2026-05-19  0.615083  0.181806  0.480017 -0.055614
2026-05-20 -1.873690 -0.581555 -0.151738 -0.640246
2026-05-21  0.001949 -0.657578 -1.566766  1.551523

In [6]:
df.tail()

                   A         B         C         D
2026-05-18  0.605085 -0.839232 -0.581135  0.229926
2026-05-19  0.615083  0.181806  0.480017 -0.055614
2026-05-20 -1.873690 -0.581555 -0.151738 -0.640246
2026-05-21  0.001949 -0.657578 -1.566766  1.551523
2026-05-22  1.045312  0.555394  1.187360 -1.022541

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')