In [1]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
# datetime index
dates = pd.date_range("20260517", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2026-05-17 -0.790204 -0.407153  2.516232  0.141701
2026-05-18  1.982904  2.723092  1.469576  0.651655
2026-05-19  1.316160 -0.041769 -0.840805  1.975672
2026-05-20  1.195035 -1.796640 -0.446025  0.131431
2026-05-21 -0.181675  0.192504  0.511078 -0.445143
2026-05-22  1.552013  0.610315  0.971681 -1.320948

In [3]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [5]:
df.head()

                   A         B         C         D
2026-05-17 -0.790204 -0.407153  2.516232  0.141701
2026-05-18  1.982904  2.723092  1.469576  0.651655
2026-05-19  1.316160 -0.041769 -0.840805  1.975672
2026-05-20  1.195035 -1.796640 -0.446025  0.131431
2026-05-21 -0.181675  0.192504  0.511078 -0.445143

In [6]:
df.tail()

                   A         B         C         D
2026-05-18  1.982904  2.723092  1.469576  0.651655
2026-05-19  1.316160 -0.041769 -0.840805  1.975672
2026-05-20  1.195035 -1.796640 -0.446025  0.131431
2026-05-21 -0.181675  0.192504  0.511078 -0.445143
2026-05-22  1.552013  0.610315  0.971681 -1.320948

In [7]:
print(df.index)
print(df.columns)

DatetimeIndex(['2026-05-17', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [8]:
# convert to numpy
df.to_numpy()

array([[-0.79020427, -0.40715272,  2.51623223,  0.14170064],
       [ 1.98290404,  2.72309244,  1.4695762 ,  0.65165535],
       [ 1.31616009, -0.04176929, -0.84080461,  1.97567244],
       [ 1.19503457, -1.79664037, -0.44602501,  0.13143127],
       [-0.18167527,  0.19250401,  0.51107812, -0.44514309],
       [ 1.55201266,  0.61031533,  0.97168141, -1.32094779]])

In [9]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [10]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [11]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.845705  0.213392  0.696956  0.189061
std    1.083251  1.479662  1.239988  1.103982
min   -0.790204 -1.796640 -0.840805 -1.320948
25%    0.162502 -0.315807 -0.206749 -0.300999
50%    1.255597  0.075367  0.741380  0.136566
75%    1.493050  0.505863  1.345103  0.524167
max    1.982904  2.723092  2.516232  1.975672

In [12]:
df.T

   2026-05-17  2026-05-18  2026-05-19  2026-05-20  2026-05-21  2026-05-22
A   -0.790204    1.982904    1.316160    1.195035   -0.181675    1.552013
B   -0.407153    2.723092   -0.041769   -1.796640    0.192504    0.610315
C    2.516232    1.469576   -0.840805   -0.446025    0.511078    0.971681
D    0.141701    0.651655    1.975672    0.131431   -0.445143   -1.320948

In [13]:
# Sort by axis
df.sort_index(axis = 1, ascending = False)

                   D         C         B         A
2026-05-17  0.141701  2.516232 -0.407153 -0.790204
2026-05-18  0.651655  1.469576  2.723092  1.982904
2026-05-19  1.975672 -0.840805 -0.041769  1.316160
2026-05-20  0.131431 -0.446025 -1.796640  1.195035
2026-05-21 -0.445143  0.511078  0.192504 -0.181675
2026-05-22 -1.320948  0.971681  0.610315  1.552013

In [14]:
# Sort by values
df.sort_values(by = "B")

                   A         B         C         D
2026-05-20  1.195035 -1.796640 -0.446025  0.131431
2026-05-17 -0.790204 -0.407153  2.516232  0.141701
2026-05-19  1.316160 -0.041769 -0.840805  1.975672
2026-05-21 -0.181675  0.192504  0.511078 -0.445143
2026-05-22  1.552013  0.610315  0.971681 -1.320948
2026-05-18  1.982904  2.723092  1.469576  0.651655